#!/usr/bin/env python

import sys, os

sys.path.append(os.path.dirname(\
                    os.path.abspath(\
                        __file__))\
                + '/libs/standalone-client.jar'
                )
print(sys.path)
